# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'altimeter' do
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'TestFairy'
end

target 'altimeterTests' do

end

